### ISSUE TITLE
Using PostgreSQL error

### ISSUE THREAD

**Issue by HackIvan** [avuletica/eLearning#12]
_**after I've downloaded all the libraries 
still give me an error**_ 

**See Error Below**

Exception ignored in thread started by: <function check_errors.<locals>.wrapper at 0x7f31fd2d5550>
Traceback (most recent call last):
  File "/home/amor/eLearning/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/amor/eLearning/venv/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/amor/eLearning/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/amor/eLearning/venv/lib/python3.8/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/amor/eLearning/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/amor/eLearning/venv/lib/python3.8/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/amor/eLearning/venv/lib/python3.8/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/amor/eLearning/venv/lib/python3.8/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/amor/eLearning/venv/lib/python3.8/site-packages/django/contrib/auth/models.py", line 4, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/home/amor/eLearning/venv/lib/python3.8/site-packages/django/contrib/auth/base_user.py", line 49, in <module>
    class AbstractBaseUser(models.Model):
RuntimeError: __class__ not set defining 'AbstractBaseUser' as <class 'django.contrib.auth.base_user.AbstractBaseUser'>. Was __classcell__ propagated to type.__new__?

**Comment by avuletica** [comment]
Hi @HackIvan ,

I'm not really active at GitHub anymore, at first glance it seems you are using a newer python version that might be causing incompatibility issues.

Please check https://github.com/avuletica/eLearning#compatibility
